use("todo_cine_dev");

// ==========================================
// RESET
// ==========================================
db.movies.drop();

// ==========================================
// INSERT MOVIES
// ==========================================

db.movies.insertMany(
    [
        {
            "id": 1357349,
            "original_language": "es",
            "original_title": "Flores para Antonio",
            "overview": "Se adentra en un emocional viaje con Alba Flores al explorar las cajas de recuerdos, cintas de ensayos y participar en el primer concierto homenaje a su padre, Antonio Flores, que se produjo el viernes 24 de noviembre de 2023 en el Palacio de Vistalegre de Madrid.",
            "popularity": 1.776,
            "poster_path": "/nxEdIdc0lOlKNa6eJtqZICC3CSm.jpg",
            "release_date": "2025-11-28",
            "title": "Flores para Antonio",
            "total_votosTC": 0,
            "vote_average": 8.5,
            "vote_count": 2,
            "votos_mediaTC": 0
        },
        {
            "id": 1433680,
            "original_language": "es",
            "original_title": "La cena",
            "overview": "España, 15 de abril de 1939. Concluida la Guerra Civil, y con intención de celebrar su victoria, el general Franco asiste con sus generales a una cena en el hotel Palace.",
            "popularity": 13.4314,
            "poster_path": "/fyWqPumuqXk32OICtKV58gFfIoq.jpg",
            "release_date": "2025-10-17",
            "title": "La cena",
            "total_votosTC": 0,
            "vote_average": 6.632,
            "vote_count": 53,
            "votos_mediaTC": 0
        },
        {
            "id": 1464374,
            "original_language": "es",
            "original_title": "Los Tigres",
            "overview": "Antonio y Estrella son hermanos buzos. Él trabaja en obras marítimas, ella estudia la vida submarina y le asiste. Su precaria economía podría mejorar tras encontrar cocaína oculta en el casco de un barco fondeado en Huelva.",
            "popularity": 11.2543,
            "poster_path": "/etJ74W3D9ZdpIk67dRSmC0akhjm.jpg",
            "release_date": "2025-10-31",
            "title": "Los Tigres",
            "total_votosTC": 0,
            "vote_average": 6.012,
            "vote_count": 42,
            "votos_mediaTC": 0
        },
        {
            "id": 1238188,
            "original_language": "es",
            "original_title": "El cautivo",
            "overview": "En 1575, el joven soldado Miguel de Cervantes es capturado en alta mar por corsarios berberiscos y llevado a Argel como rehén. Consciente de que le espera una muerte cruel si su familia no paga pronto su rescate, encuentra refugio en su pasión por contar historias.",
            "popularity": 20.7695,
            "poster_path": "/2vfxMQ3WEA8goCH7LXlAzED9aed.jpg",
            "release_date": "2025-09-12",
            "title": "El cautivo",
            "total_votosTC": 0,
            "vote_average": 6.551,
            "vote_count": 59,
            "votos_mediaTC": 0
        },
        {
            "id": 1313032,
            "original_language": "es",
            "original_title": "Ciudad sin sueño",
            "overview": "Toni, un chico de 15 años, vive en el asentamiento irregular más grande de Europa, a las afueras de Madrid. Orgulloso de pertenecer a su familia de chatarreros, sigue a su abuelo a todas partes. Pero los derribos se acercan a su parcela y su abuelo se niega a marcharse, sea cual sea el sacrificio. En oscuras noches sin electricidad, mientras las leyendas de su infancia cobran vida, Toni debe elegir: enfrentarse a un futuro incierto o aferrarse a un mundo que se desvanece.",
            "popularity": 3.035,
            "poster_path": "/l2JNUcLimAYEhbHKLuRQ44LJJO1.jpg",
            "release_date": "2025-09-03",
            "title": "Ciudad sin sueño",
            "total_votosTC": 0,
            "vote_average": 6.7,
            "vote_count": 5,
            "votos_mediaTC": 0
        },
        {
            "id": 1061771,
            "original_language": "es",
            "original_title": "Decorado",
            "overview": "En una fábula distópica llena de humor y terror, un ratón llamado Arnold se enfrenta a una crisis existencial al descubrir que su vida podría ser una gran farsa. La muerte de su mejor amigo lo lleva a cuestionar la superficialidad de las relaciones en un mundo dominado por la tecnología y las megacorporaciones.",
            "popularity": 11.5869,
            "poster_path": "/pErjlKIP9DBtcDheCpzd2GFxZyo.jpg",
            "release_date": "2025-10-24",
            "title": "Decorado",
            "total_votosTC": 0,
            "vote_average": 6.333,
            "vote_count": 6,
            "votos_mediaTC": 0
        },
        {
            "id": 975324,
            "original_language": "es",
            "original_title": "Tardes de soledad",
            "overview": "Retrato de una estrella del toreo en activo, Andrés Roca Rey, que permite reflexionar sobre la experiencia íntima del torero que asume el riesgo de enfrentarse al toro como un deber personal por respeto a la tradición y como un desafío estético.",
            "popularity": 1.749,
            "poster_path": "/uFM0LGWR6jtXuueDlAY2i9ZvlVW.jpg",
            "release_date": "2025-03-07",
            "title": "Tardes de soledad",
            "total_votosTC": 0,
            "vote_average": 7,
            "vote_count": 51,
            "votos_mediaTC": 0
        },
        {
            "id": 1386777,
            "original_language": "es",
            "original_title": "Ángulo muerto",
            "overview": "Estela y Ramón han atravesado una separación y el suicidio de Hugo, su único hijo, de tan solo 13 años, después de sufrir acoso escolar. Cuando Estela consigue un vídeo grabado por los agresores de su hijo, cree que ha llegado el momento de tener una conversación con Ramón. Mientras descubren la realidad de lo ocurrido con Hugo, tratarán de esclarecer si podrían haberlo evitado y si estuvieron a la altura como padres.",
            "popularity": 0.3113,
            "poster_path": "/8Z9uQM2twRn8zcZRgFph2yEoF2I.jpg",
            "release_date": "2026-02-19",
            "title": "Ángulo muerto",
            "total_votosTC": 0,
            "vote_average": 7,
            "vote_count": 1,
            "votos_mediaTC": 0
        },
        {
            "id": 1482484,
            "original_language": "es",
            "original_title": "El santo",
            "overview": "Documental autobiográfico que aborda temas de fe y milagros desde una perspectiva personal y familiar.",
            "popularity": 0.0554,
            "poster_path": "/jDf7ztDEWKxjXYfO5QugzTK5B3C.jpg",
            "release_date": "2025-05-18",
            "title": "El santo",
            "total_votosTC": 0,
            "vote_average": 0,
            "vote_count": 0,
            "votos_mediaTC": 0
        },
        {
            "id": 1078605,
            "original_language": "en",
            "original_title": "Weapons",
            "overview": "Cuando todos los alumnos de una misma clase, salvo uno, desaparecen misteriosamente la misma noche y exactamente a la misma hora, la pequeña ciudad donde viven se pregunta quién o qué está detrás de su desaparición.",
            "popularity": 29.7323,
            "poster_path": "/nYqEQ3ltw0hHc1kBaNWr7Rb8WNZ.jpg",
            "release_date": "2025-08-04",
            "title": "Weapons",
            "total_votosTC": 0,
            "vote_average": 7.3,
            "vote_count": 3058,
            "votos_mediaTC": 0
        },
        {
            "id": 1393151,
            "original_language": "da",
            "original_title": "Mr. Nobody mod Putin",
            "overview": "Un profesor ruso documenta en secreto la transformación de la escuela de su pequeña ciudad en un centro de reclutamiento de guerra durante la invasión de Ucrania, revelando los dilemas éticos a los que se enfrentan los educadores en medio de la propaganda y la militarización.",
            "popularity": 10.159,
            "poster_path": "/vnP69Zp2V79QCzZHVBiE5isRA4O.jpg",
            "release_date": "2025-06-06",
            "title": "Mr. Nobody contra Putin",
            "total_votosTC": 0,
            "vote_average": 7.481,
            "vote_count": 53,
            "votos_mediaTC": 0
        },
        {
            "id": 1525091,
            "original_language": "en",
            "original_title": "All the Empty Rooms",
            "overview": "En este conmovedor cortometraje documental, un periodista y un fotógrafo se proponen inmortalizar las habitaciones de niños asesinados en tiroteos escolares.",
            "popularity": 4.2854,
            "poster_path": "/cGJMjX6X5UkSUideddZho1WWDCx.jpg",
            "release_date": "2025-08-31",
            "title": "Todas las habitaciones vacías",
            "total_votosTC": 0,
            "vote_average": 7.1,
            "vote_count": 39,
            "votos_mediaTC": 0
        },
        {
            "id": 1442908,
            "original_language": "en",
            "original_title": "The Singers",
            "overview": "Cortometraje inspirado en un cuento del siglo XIX escrito por Ivan Turgenev, en el que un pub lleno de hombres oprimidos conecta inesperadamente a través de una improvisada canción.",
            "popularity": 9.9961,
            "poster_path": "/zoaPTFXCCysFz34g1hBvCfLH8Zu.jpg",
            "release_date": "2026-02-17",
            "title": "Los cantores rusos",
            "total_votosTC": 0,
            "vote_average": 6.67,
            "vote_count": 47,
            "votos_mediaTC": 0
        },
        {
            "id": 1340625,
            "original_language": "fr",
            "original_title": "Deux personnes échangeant de la salive",
            "overview": "En una sociedad donde besarse está prohibido y se castiga con la muerte, Angine, una mujer infeliz, encuentra consuelo en unas compras compulsivas. Allí conoce a Malaise, una dependienta ingenua que despierta en ella una conexión prohibida. Su cercanía pronto genera sospechas en un compañero celoso, desencadenando una tragedia absurda en un mundo represivo.",
            "popularity": 4.6458,
            "poster_path": "/mBSFvOPfkM0qzBfIaAKpS1u5IHH.jpg",
            "release_date": "2025-11-27",
            "title": "Dos personas intercambiando saliva",
            "total_votosTC": 0,
            "vote_average": 7.842,
            "vote_count": 19,
            "votos_mediaTC": 0
        },
        {
            "id": 1142149,
            "original_language": "fr",
            "original_title": "La jeune fille qui pleurait des perles",
            "overview": "En Montreal, a principios del siglo XX, un joven pobre se enamora de una joven cuyo dolor se transforma en perlas. Las vende a un prestamista despiadado, ávido de más. Tentado por la codicia, el joven debe elegir entre el amor y la fortuna.",
            "popularity": 4.7086,
            "poster_path": "/cjOHwqWD0bMlKI8CuRIK7q1cMTU.jpg",
            "release_date": "2025-06-08",
            "title": "La chica que lloraba perlas",
            "total_votosTC": 0,
            "vote_average": 7.595,
            "vote_count": 21,
            "votos_mediaTC": 0
        },
        {
            "id": 911430,
            "original_language": "en",
            "original_title": "F1",
            "overview": "El mítico piloto Sonny Hayes vuelve de su retiro, persuadido para liderar un equipo de Fórmula 1 en apuros y guiar a su joven promesa, en busca de una nueva oportunidad de éxito.",
            "popularity": 43.6856,
            "poster_path": "/wfpqaxoPKvcqzLy8FO0enGXBzU.jpg",
            "release_date": "2025-06-25",
            "title": "F1 la película",
            "total_votosTC": 0,
            "vote_average": 7.751,
            "vote_count": 3572,
            "votos_mediaTC": 0
        },
        {
            "id": 83533,
            "original_language": "en",
            "original_title": "Avatar: Fire and Ash",
            "overview": "Jake Sully y Neytiri enfrentan una nueva amenaza en Pandora: los Ash People, una tribu Na'vi violenta y sedienta de poder, liderada por la implacable Varang. Tras la devastadora guerra contra la RDA y la pérdida de su hijo mayor, la familia de Jake deberá luchar por su supervivencia y el futuro de Pandora en un conflicto que llevará a los personajes a sus límites emocionales y físicos. Con nuevos y antiguos aliados, esta épica visual y emocional redefine el destino de un mundo al borde del abismo.",
            "popularity": 93.7636,
            "poster_path": "/4n1U0Mwn7djux6VKNYDRWPgS2x6.jpg",
            "release_date": "2025-12-17",
            "title": "Avatar: Fuego y ceniza",
            "total_votosTC": 0,
            "vote_average": 7.263,
            "vote_count": 1895,
            "votos_mediaTC": 0
        },
        {
            "id": 1443576,
            "original_language": "es",
            "original_title": "Los domingos",
            "overview": "Ainara es una joven idealista y brillante de 17 años que, a priori, ha de decidir qué carrera universitaria estudiará. Sin embargo, la joven manifiesta que se siente cada vez más cerca de Dios y que está dispuesta a abrazar la vida de monja de clausura. La noticia pilla por sorpresa a toda la familia provocando un abismo y una prueba de fuego para todos.",
            "popularity": 37.7349,
            "poster_path": "/kwpDm6qtON8pLCSY0C8MltMofEE.jpg",
            "release_date": "2025-10-17",
            "title": "Los domingos",
            "total_votosTC": 0,
            "vote_average": 7.204,
            "vote_count": 76,
            "votos_mediaTC": 0
        },
        {
            "id": 1400214,
            "original_language": "eu",
            "original_title": "Maspalomas",
            "overview": "Vicente es un señor mayor abiertamente homosexual que, cuando es ingresado en una residencia, opta por volver al armario.",
            "popularity": 3.3562,
            "poster_path": "/2g5UBmSaxqwavsDrUGlf4OX2Aj3.jpg",
            "release_date": "2025-09-26",
            "title": "Maspalomas",
            "total_votosTC": 0,
            "vote_average": 6.75,
            "vote_count": 36,
            "votos_mediaTC": 0
        },
        {
            "id": 1258603,
            "original_language": "es",
            "original_title": "Cafunè",
            "overview": "Alma, una niña solitaria, revive su traumático pasado cuando su muñeca cae a la piscina, arrastrándola al naufragio de la patera del que fue la única superviviente. Luna, su rescatadora, la ayuda a superar su trauma y reconstruir su vida.",
            "popularity": 0.2,
            "poster_path": "/eamNlVYU5829iIBXUCOiBS0zR1J.jpg",
            "release_date": "2024-03-04",
            "title": "Cafunè",
            "total_votosTC": 0,
            "vote_average": 0,
            "vote_count": 0,
            "votos_mediaTC": 0
        },
        {
            "id": 1174481,
            "original_language": "ca",
            "original_title": "El 47",
            "overview": "Un acto de disidencia pacífica y el movimiento vecinal de base en 1978 transformó Barcelona...",
            "popularity": 14.66,
            "poster_path": "/1mMxQuW2b5zL6TlhvufdU1poH9n.jpg",
            "release_date": "2024-09-06",
            "title": "El 47",
            "total_votosTC": 0,
            "vote_average": 7.419,
            "vote_count": 99,
            "votos_mediaTC": 0
        },
        {
            "id": 1215185,
            "original_language": "es",
            "original_title": "La infiltrada",
            "overview": "País Vasco, España, finales de los años noventa. Una joven policía consigue infiltrarse en la despiadada banda terrorista ETA.",
            "popularity": 19.805,
            "poster_path": "/xnME9c2PEtYGBDPO4lZXAVeEu0G.jpg",
            "release_date": "2024-10-11",
            "title": "La infiltrada",
            "total_votosTC": 0,
            "vote_average": 7.263,
            "vote_count": 118,
            "votos_mediaTC": 0
        },
        {
            "id": 977548,
            "original_language": "es",
            "original_title": "Segundo premio",
            "overview": "Granada, finales de los 90...",
            "popularity": 0.5475,
            "poster_path": "/e2eQxBsDxoqpaYUy5yZosvrBuVz.jpg",
            "release_date": "2024-05-24",
            "title": "Segundo premio",
            "total_votosTC": 0,
            "vote_average": 5.6,
            "vote_count": 58,
            "votos_mediaTC": 0
        },
        {
            "id": 1160878,
            "original_language": "es",
            "original_title": "La estrella azul",
            "overview": "Años 90. Mauricio, un famoso rockero español...",
            "popularity": 1.06,
            "poster_path": "/okIqQayPcdYJUwC4qq1ALxMTgV.jpg",
            "release_date": "2024-02-23",
            "title": "La estrella azul",
            "total_votosTC": 0,
            "vote_average": 7.4,
            "vote_count": 34,
            "votos_mediaTC": 0
        },
        {
            "id": 1218193,
            "original_language": "ca",
            "original_title": "Casa en flames",
            "overview": "Montse, divorciada y con dos hijos...",
            "popularity": 2.5825,
            "poster_path": "/2qhOJFZRgXr4Q8ua8NwhNCTFv8i.jpg",
            "release_date": "2024-06-28",
            "title": "Casa en llamas",
            "total_votosTC": 0,
            "vote_average": 6.8,
            "vote_count": 86,
            "votos_mediaTC": 0
        },
        {
            "id": 1088514,
            "original_language": "es",
            "original_title": "La habitación de al lado",
            "overview": "Ingrid, una exitosa novelista...",
            "popularity": 15.83,
            "poster_path": "/aFeEXvKtKZ9wY3EMsR7yp9Izfej.jpg",
            "release_date": "2024-10-07",
            "title": "La habitación de al lado",
            "total_votosTC": 0,
            "vote_average": 6.778,
            "vote_count": 441,
            "votos_mediaTC": 0
        },
        {
            "id": 1317099,
            "original_language": "es",
            "original_title": "La guitarra flamenca de Yerai Cortés",
            "overview": "Cuando C. Tangana conoce a Yerai Cortés...",
            "popularity": 0.6475,
            "poster_path": "/nWnwmEtZSZRCRMCsakcdxuz6Grs.jpg",
            "release_date": "2024-12-20",
            "title": "La guitarra flamenca de Yerai Cortés",
            "total_votosTC": 0,
            "vote_average": 7.1,
            "vote_count": 4,
            "votos_mediaTC": 0
        },
        {
            "id": 1195100,
            "original_language": "es",
            "original_title": "Marco: la verdad inventada",
            "overview": "Enric Marco, un sindicalista español...",
            "popularity": 10.215,
            "poster_path": "/k3SrxV0MizLFJAUg9jrLSEBGbuu.jpg",
            "release_date": "2024-11-08",
            "title": "Marco: la verdad inventada",
            "total_votosTC": 0,
            "vote_average": 6.8,
            "vote_count": 20,
            "votos_mediaTC": 0
        },
        {
            "id": 1118028,
            "original_language": "es",
            "original_title": "La virgen roja",
            "overview": "Hildegart es concebida y educada por su madre Aurora...",
            "popularity": 5.9525,
            "poster_path": "/bG0EV4nQcSTsdI0RfC9RbvUGnCg.jpg",
            "release_date": "2024-09-27",
            "title": "La virgen roja",
            "total_votosTC": 0,
            "vote_average": 7.1,
            "vote_count": 130,
            "votos_mediaTC": 0
        },
        {
            "id": 1280400,
            "original_language": "es",
            "original_title": "Mariposas Negras",
            "overview": "El viaje de tres mujeres que huyen de un terreno inhabitable...",
            "popularity": 0.2175,
            "poster_path": "/csifAGt9yVtA8pbVj1lceNn2ZKI.jpg",
            "release_date": "2024-12-05",
            "title": "Mariposas negras",
            "total_votosTC": 0,
            "vote_average": 0,
            "vote_count": 0,
            "votos_mediaTC": 0
        },
        {
            "id": 1000837,
            "original_language": "pt",
            "original_title": "Ainda Estou Aqui",
            "overview": "Brasil, 1971...",
            "popularity": 56.275,
            "poster_path": "/bp8VfiqYqkQOzf6e8LBv4m53gxU.jpg",
            "release_date": "2024-09-19",
            "title": "Aún Estoy Aquí",
            "total_votosTC": 0,
            "vote_average": 8,
            "vote_count": 525,
            "votos_mediaTC": 0
        },
        {
            "id": 974950,
            "original_language": "fr",
            "original_title": "Emilia Pérez",
            "overview": "Rita, una infravalorada abogada...",
            "popularity": 28.105,
            "poster_path": "/Al1cL3oPBgnmzm0EqIRcOT6JHFg.jpg",
            "release_date": "2024-08-21",
            "title": "Emilia Pérez",
            "total_votosTC": 0,
            "vote_average": 6.732,
            "vote_count": 1509,
            "votos_mediaTC": 0
        },
        {
            "id": 1217174,
            "original_language": "es",
            "original_title": "La Gran Obra",
            "overview": "Leo y Diana, una pareja aburguesada...",
            "popularity": 0.7475,
            "poster_path": "/jc5rdnVXJ8MCAOuqVi7YDc1uFAI.jpg",
            "release_date": "2024-05-27",
            "title": "La Gran Obra",
            "total_votosTC": 0,
            "vote_average": 8,
            "vote_count": 1,
            "votos_mediaTC": 0
        },
        {
            "id": 1393865,
            "original_language": "es",
            "original_title": "Semillas de Kivu",
            "overview": "En Kivu (República Democrática del Congo)...",
            "popularity": 0.05,
            "poster_path": "/mMquEf64BfDvCWUAGl1kXy9VTnP.jpg",
            "release_date": "2022-08-25",
            "title": "Semillas de Kivu",
            "total_votosTC": 0,
            "vote_average": 7,
            "vote_count": 1,
            "votos_mediaTC": 0
        },
        {
            "id": 906126,
            "original_language": "es",
            "original_title": "La sociedad de la nieve",
            "overview": "El 13 de octubre de 1972...",
            "popularity": 95.616,
            "poster_path": "/9tkJPQb4X4VoU3S5nqLDohZijPj.jpg",
            "release_date": "2023-12-15",
            "title": "La sociedad de la nieve",
            "total_votosTC": 1,
            "vote_average": 8.046,
            "vote_count": 2668,
            "votos_mediaTC": 2
        },
        {
            "id": 1171406,
            "original_language": "es",
            "original_title": "Mientras seas tú",
            "overview": "Un verano, hace cuatro años...",
            "popularity": 16.206,
            "poster_path": "/wJ8DDxuuRS5Xpm4Dqk0lcyhK785.jpg",
            "release_date": "2024-02-09",
            "title": "Mientras seas tú",
            "total_votosTC": 1,
            "vote_average": 7,
            "vote_count": 1,
            "votos_mediaTC": 3
        },
        {
            "id": 816888,
            "original_language": "gl",
            "original_title": "O corno",
            "overview": "Illa de Arousa, 1971...",
            "popularity": 5.046,
            "poster_path": "/uaFgJcgmHniHPZdjkNE5zfhhIcQ.jpg",
            "release_date": "2023-10-11",
            "title": "O corno",
            "total_votosTC": 1,
            "vote_average": 6.393,
            "vote_count": 14,
            "votos_mediaTC": 3
        },
        {
            "id": 1053600,
            "original_language": "es",
            "original_title": "20.000 especies de abejas",
            "overview": "Cocó, de ocho años...",
            "popularity": 28.627,
            "poster_path": "/xsmddONe1QoHaMQS8ilyKA9OPtr.jpg",
            "release_date": "2023-04-21",
            "title": "20.000 especies de abejas",
            "total_votosTC": 1,
            "vote_average": 7.044,
            "vote_count": 80,
            "votos_mediaTC": 4
        },
        {
            "id": 1032760,
            "original_language": "es",
            "original_title": "La memoria infinita",
            "overview": "Augusto y Paulina llevan juntos 25 años...",
            "popularity": 44.444,
            "poster_path": "/vEptDugaobbwXmAWhv766bI6YTO.jpg",
            "release_date": "2023-08-11",
            "title": "La memoria infinita",
            "total_votosTC": 1,
            "vote_average": 8.18,
            "vote_count": 64,
            "votos_mediaTC": 2
        },
        {
            "id": 828936,
            "original_language": "es",
            "original_title": "Que nadie duerma",
            "overview": "Tras perder su empleo como programadora informática...",
            "popularity": 25.459,
            "poster_path": "/lIPC1FM9KBX8vXRG40iSJoKsZsv.jpg",
            "release_date": "2023-11-17",
            "title": "Que nadie duerma",
            "total_votosTC": 1,
            "vote_average": 5.8,
            "vote_count": 41,
            "votos_mediaTC": 5
        },
        {
            "id": 1138248,
            "original_language": "ca",
            "original_title": "Saben aquell",
            "overview": "Barcelona, España, a finales de los años sesenta...",
            "popularity": 11.221,
            "poster_path": "/43OFnIfH09qwj8uTDNKEvgAGa73.jpg",
            "release_date": "2023-11-01",
            "title": "Saben aquell",
            "total_votosTC": 1,
            "vote_average": 7.048,
            "vote_count": 42,
            "votos_mediaTC": 3
        },
        {
            "id": 997294,
            "original_language": "es",
            "original_title": "Cerrar los ojos",
            "overview": "Años después de su misteriosa desaparición...",
            "popularity": 42.655,
            "poster_path": "/1lx8cw1c1j2RTlQHgjR4phQBmVB.jpg",
            "release_date": "2023-08-16",
            "title": "Cerrar los ojos",
            "total_votosTC": 1,
            "vote_average": 6.9,
            "vote_count": 69,
            "votos_mediaTC": 4
        },
        {
            "id": 838240,
            "original_language": "es",
            "original_title": "Robot Dreams",
            "overview": "DOG es un perro solitario que vive en Manhattan...",
            "popularity": 89.087,
            "poster_path": "/rUPJfjfNEbANXQrmCQfurOppqrA.jpg",
            "release_date": "2023-12-06",
            "title": "Robot Dreams",
            "total_votosTC": 1,
            "vote_average": 8.102,
            "vote_count": 413,
            "votos_mediaTC": 4
        },
        {
            "id": 1120881,
            "original_language": "es",
            "original_title": "Aunque es de noche",
            "overview": "En \"La Cañada Real\"...",
            "popularity": 7.904,
            "poster_path": "/oNYGh6WgkAUHmpkK3dYlUGBZCj6.jpg",
            "release_date": "2023-05-17",
            "title": "Aunque es de noche",
            "total_votosTC": 1,
            "vote_average": 4.5,
            "vote_count": 4,
            "votos_mediaTC": 1
        },
        {
            "id": 1211711,
            "original_language": "es",
            "original_title": "Ava",
            "overview": "Ava es una adolescente que coge el metro...",
            "popularity": 1.792,
            "poster_path": "/oNp2eeLMDw7keAzptEvwcBI0IXb.jpg",
            "release_date": "2023-09-25",
            "title": "Ava",
            "total_votosTC": 1,
            "vote_average": 0,
            "vote_count": 0,
            "votos_mediaTC": 3
        },
        {
            "id": 1181273,
            "original_language": "xx",
            "original_title": "To Bird or Not to Bird",
            "overview": "En un mundo dominado por el ser humano...",
            "popularity": 1.629,
            "poster_path": "/aJJos5CtRX0ib4kBrrA9e8QBp2j.jpg",
            "release_date": "2023-09-23",
            "title": "To Bird or Not to Bird",
            "total_votosTC": 1,
            "vote_average": 0,
            "vote_count": 0,
            "votos_mediaTC": 2
        },
        {
            "id": 915935,
            "original_language": "fr",
            "original_title": "Anatomie d'une chute",
            "overview": "Sandra, una escritora alemana...",
            "popularity": 98.129,
            "poster_path": "/31MkIlfEaQ5vopz5lulP96xbZyU.jpg",
            "release_date": "2023-08-23",
            "title": "Anatomía de una caída",
            "total_votosTC": 1,
            "vote_average": 7.594,
            "vote_count": 2138,
            "votos_mediaTC": 4
        },
        {
            "id": 858024,
            "original_language": "en",
            "original_title": "Hamnet",
            "overview": "Descubre la poderosa historia de amor...",
            "popularity": 34.0532,
            "poster_path": "/hVo0g5M8z1kuhzxQ51eCbF81wUh.jpg",
            "release_date": "2025-11-26",
            "title": "Hamnet",
            "total_votosTC": 0,
            "vote_average": 7.6,
            "vote_count": 47,
            "votos_mediaTC": 0
        },
        {
            "id": 1054867,
            "original_language": "en",
            "original_title": "One Battle After Another",
            "overview": "Un ex revolucionario...",
            "popularity": 81.4258,
            "poster_path": "/iZ1499F6hYxDxiqioy8oSUaxipG.jpg",
            "release_date": "2025-09-23",
            "title": "Una batalla tras otra",
            "total_votosTC": 1,
            "vote_average": 7.438,
            "vote_count": 2421,
            "votos_mediaTC": 3
        },
        {
            "id": 803796,
            "original_language": "en",
            "original_title": "KPop Demon Hunters",
            "overview": "Cuando no están llenando estadios...",
            "popularity": 61.6406,
            "poster_path": "/6EQMqEmdG5HoGe2zT1WwWUMvVhv.jpg",
            "release_date": "2025-06-20",
            "title": "Las guerreras k-pop",
            "total_votosTC": 0,
            "vote_average": 8.127,
            "vote_count": 2224,
            "votos_mediaTC": 0
        },
        {
            "id": 1220564,
            "original_language": "pt",
            "original_title": "O Agente Secreto",
            "overview": "En Brasil, en 1977...",
            "popularity": 25.1957,
            "poster_path": "/t1DQ4XXIqTm5LvUjz8jypN43JjZ.jpg",
            "release_date": "2025-07-23",
            "title": "El agente secreto",
            "total_votosTC": 0,
            "vote_average": 7.914,
            "vote_count": 145,
            "votos_mediaTC": 0
        },
        {
            "id": 1317288,
            "original_language": "en",
            "original_title": "Marty Supreme",
            "overview": null,
            "popularity": 50.3609,
            "poster_path": "/mijSU0Rws3tBBbhdE5udxPSaZvF.jpg",
            "release_date": "2025-12-19",
            "title": "Marty Supreme",
            "total_votosTC": 0,
            "vote_average": 8.025,
            "vote_count": 121,
            "votos_mediaTC": 0
        },
        {
            "id": 1160360,
            "original_language": "en",
            "original_title": "If I Had Legs I'd Kick You",
            "overview": "Con su vida literalmente derrumbándose...",
            "popularity": 9.8391,
            "poster_path": "/dpXbEKk1eMcXRgl62zWhNcZH4BN.jpg",
            "release_date": "2025-10-10",
            "title": "Si pudiera, te daría una patada",
            "total_votosTC": 0,
            "vote_average": 6.59,
            "vote_count": 105,
            "votos_mediaTC": 0
        },
        {
            "id": 1124566,
            "original_language": "no",
            "original_title": "Affeksjonsverdi",
            "overview": null,
            "popularity": 20.2817,
            "poster_path": "/aRn3NkZEJIZRQyZGexMPBzUJtcp.jpg",
            "release_date": "2025-08-20",
            "title": "Valor sentimental",
            "total_votosTC": 0,
            "vote_average": 7.619,
            "vote_count": 303,
            "votos_mediaTC": 0
        },
        {
            "id": 1233413,
            "original_language": "en",
            "original_title": "Sinners",
            "overview": "Tratando de dejar atrás sus problemáticas vidas...",
            "popularity": 42.4176,
            "poster_path": "/zdClwqpYQXBSCGGDMdtvsuggwec.jpg",
            "release_date": "2025-04-16",
            "title": "Los pecadores",
            "total_votosTC": 0,
            "vote_average": 7.5,
            "vote_count": 3218,
            "votos_mediaTC": 0
        },
        {
            "id": 165,
            "original_language": "en",
            "original_title": "Back to the Future Part II",
            "overview": "Aunque a Marty McFly todavía le falta tiempo para asimilar el hecho de estar viviendo dentro de la familia perfecta gracias a su anterior viaje en el tiempo, no le queda ni espacio para respirar cuando su amigo Doc aparece de improviso con la máquina del tiempo (mucho más modernizada), e insta a que le acompañen él y su novia a viajar al futuro para solucionar un problema con la ley que tendrá uno de sus futuros hijos. En la tremenda vorágine futurista, con todo lo que ello conlleva, del Hill Valley de 2015, la presencia de tales viajeros temporales causará un efecto mayor que el que iban a arreglar. Un almanaque deportivo y la posesión del secreto de la existencia de la máquina del tiempo por parte del siempre villano Biff Tannen, serán los ingredientes que conjugarán una causa-efecto en el pasado, en el presente y en el propio futuro, que hará que Marty y Doc se tengan que emplear a fondo para poner fin a la catástrofe a la que les lleva el destino.",
            "popularity": 7.1854,
            "poster_path": "/oTiQdzBOP5biNvzvrSPAvPxiSKH.jpg",
            "release_date": "1989-11-22",
            "title": "Regreso al futuro II",
            "total_votosTC": 1,
            "vote_average": 7.775,
            "vote_count": 13684,
            "votos_mediaTC": 2
        },
        {
            "id": 1303613,
            "original_language": "es",
            "original_title": "Sorda",
            "overview": "Ángela, una mujer sorda, va a tener un bebé con Héctor, su pareja oyente. El embarazo hace aflorar sus miedos frente la maternidad y sobre cómo podrá comunicarse con su hija. La llegada de la niña genera una crisis en la pareja y lleva a Ángela a afrontar la crianza de su hija en un mundo que no está hecho para ella.",
            "popularity": 4.7253,
            "poster_path": "/hfBwdvdp11wiMqdipxIY4dOzBUC.jpg",
            "release_date": "2025-04-04",
            "title": "Sorda",
            "total_votosTC": 0,
            "vote_average": 7.3,
            "vote_count": 80,
            "votos_mediaTC": 0
        },
        {
            "id": 1151272,
            "original_language": "es",
            "original_title": "Sirāt",
            "overview": "Un hombre y su hijo que llegan a una rave perdidos en medio de lo que se describen como las áridas y fantasmagóricas montañas del sur de Marruecos.",
            "popularity": 13.9514,
            "poster_path": "/edEDZwU3kZerqdylZsyCn7feH23.jpg",
            "release_date": "2025-06-06",
            "title": "Sirat: Trance en el desierto",
            "total_votosTC": 0,
            "vote_average": 6.822,
            "vote_count": 488,
            "votos_mediaTC": 0
        },
        {
            "id": 1364216,
            "original_language": "xx",
            "original_title": "Gilbert",
            "overview": "Gilbert y Sullivan son habitantes de un pequeño archipiélago en medio del océano donde Sullivan es trompetista y Gilbert reparte paquetes con su góndola entre los habitantes de estas casas flotantes. Pero un dia Gilbert decide quedarse con un paquete.",
            "popularity": 0.1332,
            "poster_path": "/mJDHAgLM4xy65M5eKZv9JEvzYy1.jpg",
            "release_date": "2024-06-20",
            "title": "Gilbert",
            "total_votosTC": 0,
            "vote_average": 7,
            "vote_count": 2,
            "votos_mediaTC": 0
        },
        {
            "id": 1301844,
            "original_language": "es",
            "original_title": "Belén",
            "overview": "En la provincia de Tucumán, Argentina, siguen Julieta, una joven acusada de infanticidio, y Soledad Deza, la audaz abogada que lo arriesga todo para asumir su caso altamente controvertido y que sienta precedentes. A medida que se desarrolla el juicio, la difícil situación de Julieta se convierte en un punto álgido en la batalla contra un sistema legal conservador, lo que provoca una oleada de indignación y una creciente ola de solidaridad que trasciende las fronteras.",
            "popularity": 4.9732,
            "poster_path": "/w0DzNvUOjCIqxxifViNlwMSc3bm.jpg",
            "release_date": "2025-09-18",
            "title": "Belén",
            "total_votosTC": 0,
            "vote_average": 7.551,
            "vote_count": 39,
            "votos_mediaTC": 0
        }
    ]
);

// ==========================================
// MAPAS AUXILIARES
// ==========================================
const premiosMap = {
    "1": "Goya",
    "2": "Globos de oro",
    "3": "Oscars"
};

const categoriasMap = {
    "1": "Mejor película",
    "2": "Actor revelación",
    "3": "Dirección",
    "4": "Música original",
    "5": "Dirección de producción",
    "6": "Efectos especiales",
    "7": "Sonido",
    "8": "Maquillaje y peluquería",
    "9": "Dirección de fotografía",
    "10": "Diseño de vestuario",
    "11": "Montaje",
    "12": "Dirección artística",
    "13": "Actriz revelación",
    "14": "Actriz reparto",
    "15": "Dirección novel",
    "16": "Película Iberoamericana",
    "17": "Actriz protagonista",
    "18": "Actor protagonista",
    "19": "Actor reparto",
    "20": "Película de animación",
    "21": "Cortometraje de ficción",
    "22": "Cortometraje documental",
    "23": "Cortometraje de animación",
    "24": "Guión adaptado",
    "25": "Guión original",
    "26": "Película europea",
    "27": "Película documental",
    "28": "Película de habla no inglesa",
    "29": "Banda sonora",
    "30": "Canción original",
    "31": "Mejor documental",
    "32": "Mejor cortometraje",
    "33": "Mejor fotografía",
    "34": "Mejor diseño de producción",
    "35": "Mejor casting"
};

// ==========================================
// GANADORES -> EMBED EN MOVIES
// ==========================================
const ganadores = [
    ["2024","906126","1","1"],
    ["2024","906126","2","1"],
    ["2024","906126","3","1"],
    ["2024","906126","4","1"],
    ["2024","906126","5","1"],
    ["2024","906126","6","1"],
    ["2024","906126","7","1"],
    ["2024","906126","8","1"],
    ["2024","906126","9","1"],
    ["2024","906126","10","1"],
    ["2024","906126","11","1"],
    ["2024","906126","12","1"],
    ["2024","816888","13","1"],
    ["2024","1053600","14","1"],
    ["2024","1053600","15","1"],
    ["2024","1032760","16","1"],
    ["2024","828936","17","1"],
    ["2024","1138248","18","1"],
    ["2024","997294","19","1"],
    ["2024","838240","20","1"],
    ["2024","1120881","21","1"],
    ["2024","1211711","22","1"],
    ["2024","1181273","23","1"],
    ["2024","838240","24","1"],
    ["2024","1053600","25","1"],
    ["2024","915935","26","1"],
    ["2024","1171406","27","1"],

    ["2025","1174481","1","1"],
    ["2025","1215185","1","1"],
    ["2025","1160878","2","1"],
    ["2025","977548","3","1"],
    ["2025","1088514","4","1"],
    ["2025","1174481","5","1"],
    ["2025","1174481","6","1"],
    ["2025","977548","7","1"],
    ["2025","1195100","8","1"],
    ["2025","1088514","9","1"],
    ["2025","1118028","10","1"],
    ["2025","977548","11","1"],
    ["2025","1118028","12","1"],
    ["2025","1160878","13","1"],
    ["2025","1174481","14","1"],
    ["2025","1160878","15","1"],
    ["2025","1000837","16","1"],
    ["2025","1215185","17","1"],
    ["2025","1195100","18","1"],
    ["2025","1174481","19","1"],
    ["2025","1280400","20","1"],
    ["2025","1217174","21","1"],
    ["2025","1393865","22","1"],
    ["2025","1258603","23","1"],
    ["2025","1088514","24","1"],
    ["2025","1218193","25","1"],
    ["2025","974950","26","1"],
    ["2025","1317099","27","1"],

    ["2026","1443576","1","1"],
    ["2026","858024","1","2"],
    ["2026","1054867","1","2"],
    ["2026","1054867","1","3"],
    ["2026","1313032","2","1"],
    ["2026","1443576","3","1"],
    ["2026","1054867","3","2"],
    ["2026","1054867","3","3"],
    ["2026","1151272","4","1"],
    ["2026","803796","4","2"],
    ["2026","1151272","5","1"],
    ["2026","1464374","6","1"],
    ["2026","83533","6","3"],
    ["2026","1151272","7","1"],
    ["2026","911430","7","3"],
    ["2026","1238188","8","1"],
    ["2026","1151272","9","1"],
    ["2026","1433680","10","1"],
    ["2026","1151272","11","1"],
    ["2026","1054867","11","3"],
    ["2026","1151272","12","1"],
    ["2026","1303613","13","1"],
    ["2026","1443576","14","1"],
    ["2026","1054867","14","2"],
    ["2026","1078605","14","3"],
    ["2026","1303613","15","1"],
    ["2026","1301844","16","1"],
    ["2026","1443576","17","1"],
    ["2026","858024","17","2"],
    ["2026","1160360","17","2"],
    ["2026","858024","17","3"],
    ["2026","1400214","18","1"],
    ["2026","1220564","18","2"],
    ["2026","1317288","18","2"],
    ["2026","1233413","18","3"],
    ["2026","1303613","19","1"],
    ["2026","1124566","19","2"],
    ["2026","1054867","19","3"],
    ["2026","1061771","20","1"],
    ["2026","803796","20","2"],
    ["2026","803796","20","3"],
    ["2026","1386777","21","1"],
    ["2026","1482484","22","1"],
    ["2026","1525091","22","3"],
    ["2026","1364216","23","1"],
    ["2026","1142149","23","3"],
    ["2026","1433680","24","1"],
    ["2026","1054867","24","3"],
    ["2026","1443576","25","1"],
    ["2026","1054867","25","2"],
    ["2026","1233413","25","3"],
    ["2026","1124566","26","1"],
    ["2026","975324","27","1"],
    ["2026","1220564","28","2"],
    ["2026","1124566","28","3"],
    ["2026","1233413","29","2"],
    ["2026","1233413","29","3"],
    ["2026","1357349","30","1"],
    ["2026","803796","30","3"],
    ["2026","1393151","31","3"],
    ["2026","1340625","32","3"],
    ["2026","1442908","32","3"],
    ["2026","1233413","33","3"],
    ["2026","1054867","35","3"]
];

// ==========================================
// AGRUPAR PREMIOS POR MOVIE
// ==========================================
const premiosPorMovie = {};

ganadores.forEach(([anyo, movieId, categoriaId, premioId]) => {
    if (!premiosPorMovie[movieId]) {
        premiosPorMovie[movieId] = [];
    }

    premiosPorMovie[movieId].push({
        premioId: parseInt(premioId),
        titulo: premiosMap[premioId],
        categoriaId: parseInt(categoriaId),
        categoria: categoriasMap[categoriaId],
        anyo: parseInt(anyo)
    });
});

// ==========================================
// UPDATE MOVIES CON PREMIOS
// ==========================================
Object.keys(premiosPorMovie).forEach(movieId => {
    db.movies.updateOne(
        { id: parseInt(movieId) },
        {
            $set: {
                premios: premiosPorMovie[movieId]
            }
        }
    );
});

// ==========================================
// ÍNDICES
// ==========================================
db.movies.createIndex({ title: 1 });
db.movies.createIndex({ originalTitle: 1 });
db.movies.createIndex({ releaseDate: -1 });
db.movies.createIndex({ "premios.anyo": 1 });
db.movies.createIndex({ "premios.premioId": 1 });
db.movies.createIndex({ "premios.categoriaId": 1 });

print("✅ Datos cargados correctamente en MongoDB");